FROM ubuntu:24.04

RUN echo "Creating working dir and copying files"
RUN mkdir /app
WORKDIR /app
COPY . .

RUN apt update
RUN apt upgrade -y
RUN apt autoremove

RUN apt purge libkpathsea6
# LaTeX core dependencies
## amsmath is inin Ubuntu path
## /usr/share/texlive/texmf-dist/tex/latex/amsmath
RUN apt install texlive-latex-recommended -y

RUN apt install golang-go -y
RUN go clean
RUN go clean -modcache

RUN pdflatex -output-directory=assets -jobname=paper assets/paper.tex

CMD ["go", "run", "staticFileServer.go"]